### ISSUE TITLE
Login should return email address

### ISSUE THREAD

**Issue by LucasLobo** [MLH-Sprint-2/MailSafe-api#23]
The login request should return this body:

```
{
    auth_token: ...
    email: ...
}
```

**Comment by sachsom95** [comment]
https://github.com/MLH-Sprint-2/MailSafe-api/pull/24

**Comment by saksham1991999** [comment]
@sachsom95 I can work on this.

**Comment by sachsom95** [comment]
Hey Saksham we got the issue merged kept it open for a final review
closing it now
